# @package _global_
model:
  charset_train: "ঀ ঁ ং ঃঅআইঈউঊঋঌএঐওঔকখগঘঙচছজঝঞটঠডঢণতথদধনপফবভমযরলশষসহ ়ঽ া ি ী ু ূ ৃ ৄ ে ৈ ো ৌ ্ৎ ৗড়ঢ়য়ৠৡ ৢ ৣ০১২৩৪৫৬৭৮৯ৰৱ৺ 0123456789~!@#$%^&*()_-+={}[]|\"':;?/>.<,।॥‘’“”\u200c\u200d৷৳₹"
  charset_test: "ঀ ঁ ং ঃঅআইঈউঊঋঌএঐওঔকখগঘঙচছজঝঞটঠডঢণতথদধনপফবভমযরলশষসহ ়ঽ া ি ী ু ূ ৃ ৄ ে ৈ ো ৌ ্ৎ ৗড়ঢ়য়ৠৡ ৢ ৣ০১২৩৪৫৬৭৮৯ৰৱ৺ 0123456789~!@#$%^&*()_-+={}[]|\"':;?/>.<,।॥‘’“”\u200c\u200d৷৳₹"
